### ISSUE TITLE
Create class diagram

### ISSUE THREAD

**Issue by CambaSoft-dev** [CambaSoft/WebServices#13]

**Comment by JrogeT** [comment]
![class-diagram](https://user-images.githubusercontent.com/48605375/142129004-2177265b-be90-4904-91fb-ddf1c84912aa.png)

**Comment by JrogeT** [comment]
![image](https://user-images.githubusercontent.com/48605375/160264819-62625469-9fb8-4d37-b87f-b2ce466c5dad.png)
